### PR TITLE
Numbers below 1 use plural nouns, improve help

### PR DESCRIPTION
**Pull request by NMS127**
"0 missile" -> "0 missiles"

### CODE REVIEW

**Comment by gmoromisato** [comment]
Why do you need to replace > and < in the function help text? When do we output this to XML? Wouldn't it be better to escape the characters at the point that we convert to XML?

**Comment by NMS127** [comment]
It's not because it doesn't output in the help correctly, it's because you can't use < in an XML file and > is bad practice. It's not great that they're function names either...

**Comment by gcabbage** [comment]
I think the help text should stay as `<` and `>` characters as it is the help for TLisp - the escaped versions `&lt;` etc. won't work in the console or in a .tlisp file.

**Comment by gmoromisato** [comment]
What I'd like to do is recommend that people who want to use < and & use a CDATA wrapper. That's supported by the Transcendence parser.

And I agree with @gcabbage that having the escaped versions in help might be equally (if not more) confusing.

**Comment by gmoromisato** [comment]
Awesome. Thank you!

**Pull request merged**
